---
- name: Disable reverse path filtering (default)
  sysctl: >
    name=net.ipv4.conf.default.rp_filter
    value=0
    state=present
- name: Disable reverse path filtering (all)
  sysctl: >
    name=net.ipv4.conf.all.rp_filter
    value=0
    state=present
- name: Set remote file path
  set_fact: remote_file_path=/etc/modprobe.d/kvm_intel.conf
- name: Create file
  file: path="{{ remote_file_path }}" state=touch
- stat: path="{{ remote_file_path }}"
  register: file_path
- set_fact:
    file_content: |
      options kvm-intel nested=1
      options kvm-intel enable_shadow_vmcs=1
      options kvm-intel enable_apicv=1
      options kvm-intel ept=1
- copy: content="{{ file_content }}" dest="{{ remote_file_path }}"
  when: file_path.stat.exists == true
